# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  #config.vm.box = "generic/rhel7"
  config.vm.box = "ubuntu/focal64"
  #config.vm.box = "generic/rhel8"
  #config.vm.box = "generic/rhel9"

  config.vm.synced_folder '.', '/home/vagrant/foo'
  config.vm.hostname = "VMPruebas"
  config.vm.define :VMPruebas do |t|
  end

 # config.vm.network "private_network", :name => 'vboxnet0', ip: "192.168.10.241"
 # config.vm.network "private_network", :name => 'vboxnet0', ip: "192.168.56.2"
  config.vm.network "private_network", :name => '', ip: "192.168.56.2"

  config.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.name = "VMPruebas"
      vb.cpus = 2
      vb.linked_clone = true
  end
  config.vm.provision "shell", inline: <<-SHELL
    sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
    sudo systemctl restart sshd
  SHELL

end
